apiVersion: apps/v1
kind: Deployment

metadata:
  name: matriculas-api
  namespace: matriculas

spec:
  replicas: 1

  selector:
    matchLabels:
      app: matriculas-api

  template:
    metadata:
      labels:
        app: matriculas-api

    spec:
      containers:
        - name: matriculas-api
          image: matriculas-api:1.0.1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            failureThreshold: 12
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 768Mi