apiVersion: v1
kind: Secret

metadata:
  name: api-secret
  namespace: matriculas

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: matriculas_user
  SPRING_DATASOURCE_PASSWORD: matriculas_password